In [54]:
import pandas as pd
import numpy as np

df = pd.read_csv('../sample_data/455_461.csv')
df.head()

,Unnamed: 0,Timestamp,EnrollmentID,Gender,Date of birth,"Age (in years only, ex: 21,22,25)",Educational Background,"Year of Passout (ex: 2025, 2021)",Graduation Percentage (convert cgpa to percentage),"Experience (in years, freshers/pursuing students fill 0)",Industry,Height (in cms only),Where do you come from? (State/Province),Hobby,Nature,Distance you travel everyday to reach Innomatics (in km only),Native Language,Learning ability
0,0,2025/11/30 6:44:35 PM GMT+5:30,451,Male,2001-08-12,24,Bachelors,2023,68%,0.4,IT,"5'8""",Telangana,Sports,Extrovert,7km,urdu,Both
1,1,2025/11/30 6:47:51 PM GMT+5:30,81010905625,Female,2004-07-14,21,Bachelors,2025,75,0,IT,5.6 cm,Telangana,Music,Introvert,2 km,Telugu,Both
2,2,2025/11/30 6:52:20 PM GMT+5:30,81010824725,Male,2003-12-16,22,Bachelors,2025,53.4,freshers,IT,182,Andhra Pradesh,Sports,Ambivert,2,Telugu,Both
3,3,2025/11/30 6:54:05 PM GMT+5:30,81020616425,Female,1994-02-02,31,Bachelors,2016,6.24,3 years,Non-IT,151,Andhra Pradesh,Music,Ambivert,3km,Telugu,Both
4,4,2025/11/30 6:55:47 PM GMT+5:30,81010907125,Male,2004-07-10,21,Bachelors,2025,6.82,Fresher,NaN,167,Telangana,Art,Introvert,1Km,Telugu,Visual learner

In [55]:
df.shape # know no.of rows,cols

(47, 18)

In [56]:
df.columns # cols name

Index(['Unnamed: 0', 'Timestamp', 'EnrollmentID', 'Gender', 'Date of birth',
       'Age (in years only, ex: 21,22,25)', 'Educational Background',
       'Year of Passout (ex: 2025, 2021)',
       'Graduation Percentage (convert cgpa to percentage)',
       'Experience (in years, freshers/pursuing students fill 0)', 'Industry',
       'Height (in cms only)', 'Where do you come from? (State/Province)',
       'Hobby', 'Nature',
       'Distance you travel everyday to reach Innomatics (in km only)',
       'Native Language', 'Learning ability'],
      dtype='object')

In [57]:
# checking Data types
df.dtypes

Unnamed: 0                                                        int64
Timestamp                                                        object
EnrollmentID                                                     object
Gender                                                           object
Date of birth                                                    object
Age (in years only, ex: 21,22,25)                                 int64
Educational Background                                           object
Year of Passout (ex: 2025, 2021)                                 object
Graduation Percentage (convert cgpa to percentage)               object
Experience (in years, freshers/pursuing students fill 0)         object
Industry                                                         object
Height (in cms only)                                             object
Where do you come from? (State/Province)                         object
Hobby                                                            object
Nature                                                           object
Distance you travel everyday to reach Innomatics (in km only)    object
Native Language                                                  object
Learning ability                                                 object
dtype: object

In [58]:
# check missing values
df.isna().sum()

Unnamed: 0                                                       0
Timestamp                                                        0
EnrollmentID                                                     0
Gender                                                           0
Date of birth                                                    0
Age (in years only, ex: 21,22,25)                                0
Educational Background                                           0
Year of Passout (ex: 2025, 2021)                                 0
Graduation Percentage (convert cgpa to percentage)               0
Experience (in years, freshers/pursuing students fill 0)         0
Industry                                                         7
Height (in cms only)                                             0
Where do you come from? (State/Province)                         0
Hobby                                                            0
Nature                                                           0
Distance you travel everyday to reach Innomatics (in km only)    0
Native Language                                                  0
Learning ability                                                 0
dtype: int64

In [59]:
# Drop unwanted index column
df.drop(columns=["Unnamed: 0"], inplace=True)
df.head()

,Timestamp,EnrollmentID,Gender,Date of birth,"Age (in years only, ex: 21,22,25)",Educational Background,"Year of Passout (ex: 2025, 2021)",Graduation Percentage (convert cgpa to percentage),"Experience (in years, freshers/pursuing students fill 0)",Industry,Height (in cms only),Where do you come from? (State/Province),Hobby,Nature,Distance you travel everyday to reach Innomatics (in km only),Native Language,Learning ability
0,2025/11/30 6:44:35 PM GMT+5:30,451,Male,2001-08-12,24,Bachelors,2023,68%,0.4,IT,"5'8""",Telangana,Sports,Extrovert,7km,urdu,Both
1,2025/11/30 6:47:51 PM GMT+5:30,81010905625,Female,2004-07-14,21,Bachelors,2025,75,0,IT,5.6 cm,Telangana,Music,Introvert,2 km,Telugu,Both
2,2025/11/30 6:52:20 PM GMT+5:30,81010824725,Male,2003-12-16,22,Bachelors,2025,53.4,freshers,IT,182,Andhra Pradesh,Sports,Ambivert,2,Telugu,Both
3,2025/11/30 6:54:05 PM GMT+5:30,81020616425,Female,1994-02-02,31,Bachelors,2016,6.24,3 years,Non-IT,151,Andhra Pradesh,Music,Ambivert,3km,Telugu,Both
4,2025/11/30 6:55:47 PM GMT+5:30,81010907125,Male,2004-07-10,21,Bachelors,2025,6.82,Fresher,NaN,167,Telangana,Art,Introvert,1Km,Telugu,Visual learner

In [60]:
# Convert Timestamp to Datetime
df['Timestamp'] = pd.to_datetime(df['Timestamp'],errors='coerce')
df.head()

/var/folders/5b/w9f18vfx7ld6rj581l54qk5m0000gn/T/ipykernel_8928/3448806401.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Timestamp'] = pd.to_datetime(df['Timestamp'],errors='coerce')

,Timestamp,EnrollmentID,Gender,Date of birth,"Age (in years only, ex: 21,22,25)",Educational Background,"Year of Passout (ex: 2025, 2021)",Graduation Percentage (convert cgpa to percentage),"Experience (in years, freshers/pursuing students fill 0)",Industry,Height (in cms only),Where do you come from? (State/Province),Hobby,Nature,Distance you travel everyday to reach Innomatics (in km only),Native Language,Learning ability
0,2025-11-30 18:44:35-05:30,451,Male,2001-08-12,24,Bachelors,2023,68%,0.4,IT,"5'8""",Telangana,Sports,Extrovert,7km,urdu,Both
1,2025-11-30 18:47:51-05:30,81010905625,Female,2004-07-14,21,Bachelors,2025,75,0,IT,5.6 cm,Telangana,Music,Introvert,2 km,Telugu,Both
2,2025-11-30 18:52:20-05:30,81010824725,Male,2003-12-16,22,Bachelors,2025,53.4,freshers,IT,182,Andhra Pradesh,Sports,Ambivert,2,Telugu,Both
3,2025-11-30 18:54:05-05:30,81020616425,Female,1994-02-02,31,Bachelors,2016,6.24,3 years,Non-IT,151,Andhra Pradesh,Music,Ambivert,3km,Telugu,Both
4,2025-11-30 18:55:47-05:30,81010907125,Male,2004-07-10,21,Bachelors,2025,6.82,Fresher,NaN,167,Telangana,Art,Introvert,1Km,Telugu,Visual learner

In [61]:
# Convert Date of Birth to Datetime
df['Date of birth'] = pd.to_datetime(df['Date of birth'],errors='coerce')
df.head()

,Timestamp,EnrollmentID,Gender,Date of birth,"Age (in years only, ex: 21,22,25)",Educational Background,"Year of Passout (ex: 2025, 2021)",Graduation Percentage (convert cgpa to percentage),"Experience (in years, freshers/pursuing students fill 0)",Industry,Height (in cms only),Where do you come from? (State/Province),Hobby,Nature,Distance you travel everyday to reach Innomatics (in km only),Native Language,Learning ability
0,2025-11-30 18:44:35-05:30,451,Male,2001-08-12,24,Bachelors,2023,68%,0.4,IT,"5'8""",Telangana,Sports,Extrovert,7km,urdu,Both
1,2025-11-30 18:47:51-05:30,81010905625,Female,2004-07-14,21,Bachelors,2025,75,0,IT,5.6 cm,Telangana,Music,Introvert,2 km,Telugu,Both
2,2025-11-30 18:52:20-05:30,81010824725,Male,2003-12-16,22,Bachelors,2025,53.4,freshers,IT,182,Andhra Pradesh,Sports,Ambivert,2,Telugu,Both
3,2025-11-30 18:54:05-05:30,81020616425,Female,1994-02-02,31,Bachelors,2016,6.24,3 years,Non-IT,151,Andhra Pradesh,Music,Ambivert,3km,Telugu,Both
4,2025-11-30 18:55:47-05:30,81010907125,Male,2004-07-10,21,Bachelors,2025,6.82,Fresher,NaN,167,Telangana,Art,Introvert,1Km,Telugu,Visual learner

In [62]:
# Graduation Percentage(cgpa to %)
# first inspect values
df["Graduation Percentage (convert cgpa to percentage)"].unique()

array(['68%', '75', '53.4', '6.24', '6.82', '74', '75%', '70', '83',
       '80%', '63.8', '7.92', '77', '67', '78.19', '81.7', '66', '77.7%',
       '88', '80', '7.2', '85.5', '79%', '74.5', '81', '76', '7.75',
       '80.7', '70 %', '69', '89.65', '7.82', '71', '72', '70%', '74.89%',
       '7'], dtype=object)

In [63]:
# function
def clean_percentage(val):
    if pd.isna(val):
        return np.nan
    val = str(val).replace('%',"").strip()
    try:
        val = float(val)
        if val <= 10:        # CGPA
            return val * 9.5
        return val
    except:
        return np.nan

In [64]:
# creating a new column
df["Graduation Percentage"] = df["Graduation Percentage (convert cgpa to percentage)"].apply(clean_percentage)

In [65]:
# drop old col
df.drop(columns=["Graduation Percentage (convert cgpa to percentage)"], inplace=True)

In [66]:
df.head()

,Timestamp,EnrollmentID,Gender,Date of birth,"Age (in years only, ex: 21,22,25)",Educational Background,"Year of Passout (ex: 2025, 2021)","Experience (in years, freshers/pursuing students fill 0)",Industry,Height (in cms only),Where do you come from? (State/Province),Hobby,Nature,Distance you travel everyday to reach Innomatics (in km only),Native Language,Learning ability,Graduation Percentage
0,2025-11-30 18:44:35-05:30,451,Male,2001-08-12,24,Bachelors,2023,0.4,IT,"5'8""",Telangana,Sports,Extrovert,7km,urdu,Both,68.00
1,2025-11-30 18:47:51-05:30,81010905625,Female,2004-07-14,21,Bachelors,2025,0,IT,5.6 cm,Telangana,Music,Introvert,2 km,Telugu,Both,75.00
2,2025-11-30 18:52:20-05:30,81010824725,Male,2003-12-16,22,Bachelors,2025,freshers,IT,182,Andhra Pradesh,Sports,Ambivert,2,Telugu,Both,53.40
3,2025-11-30 18:54:05-05:30,81020616425,Female,1994-02-02,31,Bachelors,2016,3 years,Non-IT,151,Andhra Pradesh,Music,Ambivert,3km,Telugu,Both,59.28
4,2025-11-30 18:55:47-05:30,81010907125,Male,2004-07-10,21,Bachelors,2025,Fresher,NaN,167,Telangana,Art,Introvert,1Km,Telugu,Visual learner,64.79

In [67]:
# Clean Experience col
# inspect values
df["Experience (in years, freshers/pursuing students fill 0)"].unique()

array(['0.4', '0', 'freshers', '3 years ', 'Fresher', 'Freshers ', '1',
       '3 years 9 months', '3', 'Freshers', 'fresher', 'No experience'],
      dtype=object)

In [68]:
df["Experience (in years)"] = (
    df["Experience (in years, freshers/pursuing students fill 0)"]
    .astype(str)
    .str.extract(r"(\d+\.?\d*)") # Extracts integer or decimal numbers from mixed text (e.g., "3 years", "0.4 yrs") using regex
    .astype(float)
    .fillna(0)
)

In [69]:
df.drop(columns=["Experience (in years, freshers/pursuing students fill 0)"], inplace=True)

In [70]:
df.head()

,Timestamp,EnrollmentID,Gender,Date of birth,"Age (in years only, ex: 21,22,25)",Educational Background,"Year of Passout (ex: 2025, 2021)",Industry,Height (in cms only),Where do you come from? (State/Province),Hobby,Nature,Distance you travel everyday to reach Innomatics (in km only),Native Language,Learning ability,Graduation Percentage,Experience (in years)
0,2025-11-30 18:44:35-05:30,451,Male,2001-08-12,24,Bachelors,2023,IT,"5'8""",Telangana,Sports,Extrovert,7km,urdu,Both,68.00,0.4
1,2025-11-30 18:47:51-05:30,81010905625,Female,2004-07-14,21,Bachelors,2025,IT,5.6 cm,Telangana,Music,Introvert,2 km,Telugu,Both,75.00,0.0
2,2025-11-30 18:52:20-05:30,81010824725,Male,2003-12-16,22,Bachelors,2025,IT,182,Andhra Pradesh,Sports,Ambivert,2,Telugu,Both,53.40,0.0
3,2025-11-30 18:54:05-05:30,81020616425,Female,1994-02-02,31,Bachelors,2016,Non-IT,151,Andhra Pradesh,Music,Ambivert,3km,Telugu,Both,59.28,3.0
4,2025-11-30 18:55:47-05:30,81010907125,Male,2004-07-10,21,Bachelors,2025,NaN,167,Telangana,Art,Introvert,1Km,Telugu,Visual learner,64.79,0.0

In [71]:
# Clean Distance column
df["Distance you travel everyday to reach Innomatics (in km only)"].unique()

array(['7km', '2 km', '2', '3km', '1Km', '2km', '8', '10', '26.6km', '80',
       '0.5 km', '25', '8.5 km', '20km', '0.2', '17', '30', '7', '13km',
       '18kms', '10.5', '6 km', '1', '5km', '3.5', '1.2', '0.5', '10km',
       '1km', '15', '700m', '3 km', '9'], dtype=object)

In [72]:
df["Daily Travel Distance (km)"] = (
    df["Distance you travel everyday to reach Innomatics (in km only)"]
    .str.lower()
    .str.replace("km", "", regex=False)
    .str.strip()
)

df["Daily Travel Distance (km)"] = pd.to_numeric(
    df["Daily Travel Distance (km)"], errors="coerce"
)

df["Daily Travel Distance (km)"].fillna(
    df["Daily Travel Distance (km)"].median(),
    inplace=True
)

In [73]:
df.drop(columns=["Distance you travel everyday to reach Innomatics (in km only)"], inplace=True)

In [74]:
df.head()

,Timestamp,EnrollmentID,Gender,Date of birth,"Age (in years only, ex: 21,22,25)",Educational Background,"Year of Passout (ex: 2025, 2021)",Industry,Height (in cms only),Where do you come from? (State/Province),Hobby,Nature,Native Language,Learning ability,Graduation Percentage,Experience (in years),Daily Travel Distance (km)
0,2025-11-30 18:44:35-05:30,451,Male,2001-08-12,24,Bachelors,2023,IT,"5'8""",Telangana,Sports,Extrovert,urdu,Both,68.00,0.4,7.0
1,2025-11-30 18:47:51-05:30,81010905625,Female,2004-07-14,21,Bachelors,2025,IT,5.6 cm,Telangana,Music,Introvert,Telugu,Both,75.00,0.0,2.0
2,2025-11-30 18:52:20-05:30,81010824725,Male,2003-12-16,22,Bachelors,2025,IT,182,Andhra Pradesh,Sports,Ambivert,Telugu,Both,53.40,0.0,2.0
3,2025-11-30 18:54:05-05:30,81020616425,Female,1994-02-02,31,Bachelors,2016,Non-IT,151,Andhra Pradesh,Music,Ambivert,Telugu,Both,59.28,3.0,3.0
4,2025-11-30 18:55:47-05:30,81010907125,Male,2004-07-10,21,Bachelors,2025,NaN,167,Telangana,Art,Introvert,Telugu,Visual learner,64.79,0.0,1.0

In [75]:
# Standardize Gender Column
df["Gender"] = df["Gender"].str.capitalize()

In [76]:
# Handle Missing Industry Values
df["Industry"] = df["Industry"].fillna("Not Specified")

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 17 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Timestamp                                 47 non-null     datetime64[ns, UTC-05:30]
 1   EnrollmentID                              47 non-null     object
 2   Gender                                    47 non-null     object
 3   Date of birth                             47 non-null     datetime64[ns]
 4   Age (in years only, ex: 21,22,25)         47 non-null     int64
 5   Educational Background                    47 non-null     object
 6   Year of Passout (ex: 2025, 2021)          47 non-null     object
 7   Industry                                  47 non-null     object
 8   Height (in cms only)                      47 non-null     object
 9   Where do you come from? (State/Province)  47 non-null     object
 10  Hobby                                     47 non-null     object
 11  Nature                                    47 non-null     object
 12  Native Language                           47 non-null     object
 13  Learning ability                          47 non-null     object
 14  Graduation Percentage                     47 non-null     float64
 15  Experience (in years)                     47 non-null     float64
 16  Daily Travel Distance (km)                47 non-null     float64
dtypes: datetime64[ns, UTC-05:30](1), datetime64[ns](1), float64(3), int64(1), object(11)
memory usage: 6.4+ KB

In [78]:
df.isna().sum()

Timestamp                                   0
EnrollmentID                                0
Gender                                      0
Date of birth                               0
Age (in years only, ex: 21,22,25)           0
Educational Background                      0
Year of Passout (ex: 2025, 2021)            0
Industry                                    0
Height (in cms only)                        0
Where do you come from? (State/Province)    0
Hobby                                       0
Nature                                      0
Native Language                             0
Learning ability                            0
Graduation Percentage                       0
Experience (in years)                       0
Daily Travel Distance (km)                  0
dtype: int64

In [80]:
# to save the cleaned data
df.to_csv('../sample_data/cleaned_dataset.csv', index=False)