In [1]:
import pandas as pd

In [2]:
dict1 ={
    'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv','Mittal','Archana'],
    'Marks':[98,89,99,87,90,83,99],
    'Gender':['Male','Female','Female','Male','Male','Female','Female']
}
df1=pd.DataFrame(dict1)
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [3]:
# 1. displaying top 3 rows of dataset
df1.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

In [4]:
# 2. check last 3 rows of dataset
df1.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [5]:
# 3. Find shape of dataset(Number of rows and cols)
print(df1.shape)
print('Number of rows', df1.shape[0])
print('Number of cols', df1.shape[1])

(7, 3)
Number of rows 7
Number of cols 3

In [6]:
# 4. get info about dataset like no.of rows, no.of cols, datatype of each col and memory
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [7]:
# 5. check null of dataset
# df1.isnull() # prints boolean
df1.isnull().sum() # prints as summary col name and total count
# df1.isnull().sum(axis=1) # prints null values row wise
# df1.isnull().sum(axis=0) # prints null values col wise

Name      0
Marks     0
Gender    0
dtype: int64

In [8]:
# 6. get overall statistics of data frame
# df1.describe() # by default describe() method gives only statistics of numerical value col
# to print inlcuding numerical and categorical use include='all'
df1.describe(include='all')

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

In [9]:
# 7. find unique values of gender col
df1['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [10]:
# 8. find number of unique values of gender col
df1['Gender'].nunique()

2

In [11]:
# 9. display count of Unique values in gender col
df1['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

In [12]:
# 10. find total no.of students having marks between 90 and 100
# df1[df1['Marks']>=90] # shows only records who scored 90 or more marks
df1[(df1['Marks']>=90) & (df1['Marks']<=100)]

# using between method
# df1['Marks'].between(90,100) # both 90 and 100 are included

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [13]:
# 11. find average of marks
df1['Marks'].mean()

# df1['Marks'].min() # minimum of marks
# df1['Marks'].max() # maximum of marks

np.float64(92.14285714285714)

In [14]:
# 12. Apply method
def marks(x):
    return x//2

df1['Marks'].apply(marks)

df1['Half_Marks'] = df1['Marks'].apply(marks)
df1

      Name  Marks  Gender  Half_Marks
0  Priyang     98    Male          49
1   Aadhya     89  Female          44
2   Krisha     99  Female          49
3   Vedant     87    Male          43
4   Parshv     90    Male          45
5   Mittal     83  Female          41
6  Archana     99  Female          49

In [15]:
df1['Marks'].apply(lambda x: x/2)

# df1['Name'].apply(len) # prints length of string

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

In [16]:
# 13. Map Function
# need to change Male - 1 and Female - 0

df1['Male_Female'] = df1['Gender'].map({'Male': 1, 'Female': 0})
df1

      Name  Marks  Gender  Half_Marks  Male_Female
0  Priyang     98    Male          49            1
1   Aadhya     89  Female          44            0
2   Krisha     99  Female          49            0
3   Vedant     87    Male          43            1
4   Parshv     90    Male          45            1
5   Mittal     83  Female          41            0
6  Archana     99  Female          49            0

In [17]:
# 14. drop the cols
# df1.drop('Male_Female',axis =1) # it will drop single column
df1.drop(['Male_Female','Half_Marks'],axis=1,inplace=True) # to drop multiple cols use list
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [18]:
# 15. print names of columns
df1.columns

# df1.index # prints the index's start, stop and step

Index(['Name', 'Marks', 'Gender'], dtype='object')

In [19]:
# 16. sort the data frame as per marks column
# df1.sort_values(by='Marks', ascending=False) # by default ascending order
df1.sort_values(by=['Marks','Gender'], ascending=False) # sorting based on multiple values

      Name  Marks  Gender
2   Krisha     99  Female
6  Archana     99  Female
0  Priyang     98    Male
4   Parshv     90    Male
1   Aadhya     89  Female
3   Vedant     87    Male
5   Mittal     83  Female

In [20]:
# 17. Display name and marks of female students
df1[df1['Gender'] == 'Female'][['Name','Marks']]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99

In [21]:
import seaborn as sns
p = sns.load_dataset('tips')
p

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [22]:
p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB